### ISSUE TITLE
Build out the new-campaign/address page

### ISSUE THREAD

**Issue by chompasina** [codefordenver/Circular#129]
As as user, 
when I type in an address that does not already have a campaign,
I am taken to a new route, called new-campaign/address page.

Expected outcome: this page will have the address I entered listed and will ask for the name of my building if appropriate. At the bottom of the form is a button for Next.

Form Data:
address
name of campaign (eg apartment complex name)

**Comment by ximsce** [comment]
I rebased master on this branch, but still couldn't get the endpoint to work. it looks like some magic on the ruby side isn't quite working with the way the react app submits the post request. Can someone with a little more ruby take a look at this? Otherwise, let's try to get this working on monday.
