### ISSUE TITLE
Contact City of Denver

### ISSUE THREAD

**Issue by adamszabunio** [codefordenver/Circular#17]

**Comment by dowgy** [comment]
Rob to contact City of Denver waste management

**Comment by robsedivy** [comment]
I sent an email out to Courtney, the Recycling Program Manager at the City of Denver... Hopefully she can make it to next week's meeting. I'm still awaiting a response, but here is a copy of the email:

Hi Courtney,

We recently exchanged some correspondence regarding recycling collection for multi-family buildings with eight or more units - Thanks again for providing that information. I learned that recycling collection service for tenants of large multi-family buildings was at the discretion of the landlord. The landlord, as a commercial property owner, must coordinate private service through one of the various hauling contractors operating in Denver. Obviously, tenants have the ability to request that the service be provided, but the landlord is not required to oblige. The City of Denver has a set of recommended steps and tips for making an effective request listed on their site, but I was wondering if we could do more to simplify the process for both the tenants and the landlord in order to increase the likelihood that requests come to fruition. 

I'm a member of Code for Denver (http://www.codefordenver.org/). We partner with local non-profits, governments, and community groups to develop apps and websites that benefit the greater-good. During yesterday's meeting, I proposed the idea of developing a webtool for tenants of large dwellings to collectively request that their landlord provide recycling service. The project received significant interest and we would love to move forward with it.
 
The primary goal of the project is to provide tenants with the ability to transparently and collectively petition their landlord, through an automated and highly efficient process. The flow of the tool would be as follows:

1. A tenant creates an online campaign to petition their landlord for recycling collection. Information regarding landlord contact details, building occupancy, existing waste capacity and hauling company, etc is collected. An 8.5" x 11" poster is generated for print and used to advertise the campaign in common areas of the building such as a lobby, mail room, or hallway. The poster provides a link to the building’s campaign where tenants can access and sign their building's online petition. This link can also be electronically distributed if a channel is available. 

2. Tenants can track the progress of their petition.  
 
3. The collection companies will submit standardized bids specifically tailored to the building’s collection needs (size and schedule) through the tool.   

3. After a 1 or 2-week sign and comment period, the petition, along with supplemental information and resources, is delivered to the landlord either electronically, physically, or both. A copy will also be emailed to each tenant that signed the petition. The deliverable will include the following:
a.      Statement regarding the benefits of recycling. 
b.      Signed petition highlighting the number and overall fraction of tenants requesting recycling collection. 
c.      An informational guide on available service providers and tips, including how to calculate the reduction in trash collection services if recycling is adopted. The landlord will also be provided with a set of recent tailored bids from local collection companies.

4. The landlord then reviews the deliverable and commits to providing recycling collection for the building or denies the request. He or she will have the ability to respond to tenants through the tool.
 
5. If successful, the tenants and landlord will be sent a guide on how to properly recycle. If not, then the app will inform them of alternative options such as the nearest centralized collection point.
 
6. Data will be collected and mapped to visualize the adoption or denial of recycling collection. The data will be utilized to measure the efficacy of the tool, and provided to the public for their use. 

All of this is preliminary, and features may be added or removed as feedback is provided and the project evolves. Also, we intend to eventually add the ability to request compost collection, but will focus on recycling for the initial build-out. 

In order to move the project forward we need an outside stakeholder, typically a non-profit or municipality connected to the issue at hand, that will provide feedback as we develop the site and support the launch of the project. We believe that the Denver Solid Waste Management/Recycling Program would be an optimal partner in this regard. Would you have time to discuss your potential involvement in the project during the next week? We meet on Monday evenings from 6-9 pm at 1062 Delaware Street (Galvanize), but I am also available to speak by phone or meet before work for a coffee, as well as after. Please let me know what is most convenient for you. 

Thanks for taking the time to consider this – I really hope that we can work together on this project and cause. I hope to hear from you soon! 

Rob

Rob Sedivy, EIT, ENV SP | Environmental Engineer
(708) 856-2816 | RobSedivy@gmail.com

**Comment by adamszabunio** [comment]
Rob, 

Great email. Very well thought out on each point. I think you may have just set the template for the project. 

Hopefully we hear back from Courtney soon. 

On my end, I haven’t done much besides discovering this open source website:

https://batchgeo.com/ <https://batchgeo.com/>

In the future, this could be just what we are looking for in terms of dropping a pin for each apartment complex and creating potential routes for the recycling/compost companies. 

Cheers, 

Adam

**Comment by robsedivy** [comment]
Hey everyone: Initial response from Courtney was very positive, but after speaking with her boss they became concerned that publicly supporting our project may constitute a conflict of interest in the event that future legislation regarding recycling comes up... The Office of Sustainability has also joined the conversation and is supportive of the project, but hasn't offered to partner with us. They did, however, mention that we should consider some other agencies to partner with. Also, they would like us to attend the Sustainability Summit in November and potentially advance our project there. We can discuss this all in detail on Monday - I'm still working on getting clarification on a few items. 

Rob
