### ISSUE TITLE
Add status bar to the campaign page to reflect the campaign's progress

### ISSUE THREAD

**Issue by chompasina** [codefordenver/Circular#204]
![image](https://user-images.githubusercontent.com/15034459/32407538-43163210-c150-11e7-866a-658fac3e974c.png)

- Create Campaign
- Print Flyer
- Gather Signatures
- Request Recycling

**Comment by robsedivy** [comment]
Updated timer graphic: https://drive.google.com/open?id=1M1WJNC69pQorLH5ZgI7hrRfvhYgWk0pA

Add a countdown timer bar to the campaign page that shows the days remaining to landlord contact day. 

When a campaign page is created, tenants are provided a limited amount of time to complete their petition. The purpose of this feature is to keep campaigns from going stagnant, as well as to set a date for a concerted landlord contact effort. 

If possible, have landlord contact day snap to the first Monday after 3 weeks so that the landlord is likely to be available for contact (unlike a weekend).

**Comment by TheBrooks** [comment]
The progress bar is in but the current logic is 15 days.  Update the progress bar date logic to snap to the first monday after 3 weeks.
