### ISSUE TITLE
After signing campaign, render signature on the page w/o requiring refresh

### ISSUE THREAD

**Issue by JasminBarco** [codefordenver/Circular#264]
As a user,  when I sign the petition, I wish to see my and my neighbor's signature on the page immediately without having to refresh. (Have signature list open by default instead of collapsed).

**Comment by chompasina** [comment]
I also think we don't want to sign users out automatically anymore, since we want them to be able to participate in the comment section and currently to do so, you would need to sign in with GOogle to sign the petition, and then click the google button again to participate in the comment section. Maybe we add a separate google button with a sign out?

**Comment by hoop71** [comment]
Solved these with #297
