### ISSUE TITLE
Write tests to cover the test cases

### ISSUE THREAD

**Issue by LaurieLinz** [codefordenver/Circular#268]
Test Cases are here: https://drive.google.com/drive/folders/1obtB1bMOm_DdY7t7jSrrMLE_lVbiKZ7z

Some tests were added with #247

**Comment by dwhite96** [comment]
@scottfirestone, I assigned you to this issue since you mentioned you wanted to write some tests. I hope I didn't overstep my bounds :). Like you said, I thought we should make sure we're not working on the same thing. I'll continue on with some landing page integration tests for now. I may look into unit testing with Cypress to learn how that works but will let you know before I start writing them. If you want to take on another page of the app, just respond to this message. Let me know if there's a better way to handle more than one assignee on an issue using Github/Waffle without stepping on each others toes. I'm usually using Github by myself and not on a team. 

Thanks for fixing the Travis CI issue! I'm hoping I can get some tests committed this weekend.
