### ISSUE TITLE
tips for requesting recycling page

### ISSUE THREAD

**Issue by TheBrooks** [codefordenver/Circular#291]
This page is currently linked to from the campaign page (and will be added to the tools dropdown on the navbar)
Currently this page does not have any text on it.  

Flesh out this page and add it to the navbar.

**Comment by JasminBarco** [comment]
Hey @TheBrooks, I almost see this as #281, build out "now what"page. This page has tips for "approaching your landlord" which to me is the same as tips for requesting recycling, at least in MFC's.  Perhaps it makes more sense to take our the approaching your landlord tab and add it to the tips for requesting recycling page. 
We can add another tab for tips for requesting recycling services which can include the list of licensed haulers in Denver, however I can see this being as problematic since the customer is the property management company, not the tenant. This could pose more problems for management companies or landlords. 

The city has a good page on requesting recycling services for MFC's we can link to: 
http://www.denvergov.org/content/denvergov/en/trash-and-recycling/resources/apartment---multi-family-recycling.html 

this includes a list of hauler and articles on how to get service. I hope this helps!

**Comment by TheBrooks** [comment]
I think we can consolodate the Now What page and the Tips for Requesting page into a single page.

Dividing out the pages info too thin could make it hard for a user to find a page they previously saw.  especially when the information represented on each is not too different.  

We can link it to the Now What page (although i would recommend titling it something more descriptive of the information it holds) and add more tabs like you said.  
- Hauling information tab with link


If this sounds like a good idea lmk.  
Also do you think renaming the 'Now What?' page to Tips for Requesting would be a good change?

**Comment by JasminBarco** [comment]
Sounds good! Yes, we can rename the Now What to Tips for Requesting Service
