### ISSUE TITLE
Build out Denver "Learn More"page

### ISSUE THREAD

**Issue by chompasina** [codefordenver/Circular#45]
As a user when I go to the Recycling Request Tool homepage, I scroll down past the address input field and click on the bottom left "Learn More" (about recycling in Denver) link.
![Screen Shot 2018-02-22 at 19.49.53.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/584619e37a5c7e1300b983de/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216456f16b7191a379e60c2f58415a4dbe5d4a1f06a3a3dc78e2a436628f5b58e985395970c76e42aeb08b1ebb01ba28881e8db7b59850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec951f54ee54f57a711376af43b.png)

**Comment by ScorchConway** [comment]
This page will probably be accessible from the "Learn More" link, currently on the bottom-right of the landing page.  It will probably contain copy provided by ecocycle.

**Comment by JasminBarco** [comment]
Why Zero Waste?
http://ecocyclesolutionshub.org/about-zero-waste/ 

Community Organizing for Zero Waste
http://ecocyclesolutionshub.org/take-action/community-organizing-for-zero-waste/

Making room for Recycling
http://ecocyclesolutionshub.org/making-room-for-recycling/

**Comment by JasminBarco** [comment]
Denver, we can do A LOT better than 20%!
Denver recycles and composts only 20% of its waste, far behind the national average of 34%. Curbside recycling is available only to most single-family residents--not to multi-family properties or businesses--and only 6% of Denver residents have composting collection.  Multi-family and businesses are said to recycle and compost 22% of their waste- still a lot of room for improvement! 

Denver is falling behind on the basics of recycling at a time when major cities, including San Francisco, New York and Los Angeles, have set Zero Waste goals. Even Denver's peer cities, such as Salt Lake City, UT; Charlotte, NC; and Austin, TX, recycle twice as much as Denver. See how Denver compares on recycling to its peers.

It's time to speak up and make better recycling and composting a priority for Denver! Get involved by signing our letter to Mayor Hancock.  (http://ecocycle.org/take-action/denver)

**Comment by JasminBarco** [comment]
Why Recycle? **Tab** 
Recycling is known as the Climate Solution's best ket secret. Recycling is not about the materials kept in the economy, it's about the energy saved in making all of your things. 

Energy Savings in: 
Mining Natural Resources
Transportation
Manufacturing 

When you recycle, you give a material a second life. Plastic bottles can become new things like carpet or clothing; aluminum cans and other metals are easily melted and made into new products. 
Don't "feed the 'fill". Recycle and compost instead. 

Tips for Recycling **Tab** 
PDF's with recycling guidelines (City of Denver and other haulers?) TO BE ADDED

Common Myths **Tab**
"Most of my recycling goes to the landfill"
Heavily contaminated loads do sometimes make it to the landfill. Recycling is a commodity, a clean product needs to be sorted at the Materials Recovery Facility (MRF) and is then sent to different markets worldwide. 
When a load is "too contaminated", it's barely distinguishable from your trash dumpster! There are organic materials, plastic bags, paper towels, appliances and even electronics! Most property managers are reluctant to provide recycling services for fear of contamination. When a bin is too contaminated, the property has the option of 1. cleaning out the recycling bin or 2. getting charged extra to haul the recyclables away as trash. 

"Landfills are ok, they recover energy""
While modern landfills are incorporating "waste to energy" methane capture, over a landfill's lifespan, only 20% of the methane gas is adequately captured. The rest goes up to the atmosphere. 
Methane is 80x stronger than CO2! 

"All plastic is recyclable"
Remember how we mentioned plastic bags are considered contamination? All of your recyclables go to a big  machine which separates materials. Aluminum with aluminum, glass with glass, paper with paper, cardboard with cardboard and so on. Plastic bags are very lightweight, they can actually get stuck in between the machine's gear and clog it. 
Make sure your neighbors  DON'T add "tanglers" like headphones or christmas lights. 

FAQ's **Tab** 
1. What happens if I live in....?
Check your city's waste regulations. 
Some cities have municipally run systems like Denver, others have open markers like Boulder, others have a single hauler like Golden and Commerce City.

**Comment by JasminBarco** [comment]
![Screen Shot 2018-02-22 at 20.27.26.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/584619e37a5c7e1300b983de/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216456f16b7191a37aef0c2956415d48be5d4a1f06a3a3dc78e2a436628f5b58e985395970c76e42aeb08b1ebb01ba28881e8db7b59850d2aa6c7bb3d4d216744b470a83ed5c3daa984ec951f54ee74b53a5103360f43b.png)
